#!/bin/sh

set -e

# Enable all repositories and backports (for zfs).
lb config noauto \
	--architectures amd64 \
	--system live \
	--updates true \
	--backports true \
	--security true \
	--archive-areas "main contrib non-free" \
	--debian-installer live \
	--bootappend-live "boot=live components hostname=sctech" \
	--linux-packages "linux-image linux-headers" \
	--mirror-binary http://mirrors.dotsrc.org/debian/ \
	--mirror-bootstrap http://mirrors.dotsrc.org/debian/ \
    --clean \
	"$@"
